### ISSUE TITLE
Error When visit Profile Page 

### ISSUE THREAD

**Issue by PraveenMalethia** [divanov11/Mumble#411] opened 2021-05-26 02:00 UTC
### Describe the bug

A clear and concise description of what the bug is that when I visit the profile page. it is just blank! total white 

### Screenshots

![image](https://user-images.githubusercontent.com/59171685/119591444-3b549180-bdf4-11eb-8999-3ac84ab85daa.png)

**Comment by codyseibert** [comment] 2021-05-26 03:31
I think this was fixed with the latest deploy to master.  Closing for now since I can't reproduce.

**Closed by codyseibert** 2021-05-26 03:31 UTC
Labels: bug
